### ISSUE TITLE
Jungle grass appears in the wrong places.

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#387]
> > Controlling both biome and height is possible via DEM files: 
> > https://github.com/bobombolo/realterrain
> -Poikilos
> 
> New implementation of voxel_manip in Final Minetest has broken and 
> jumbled all the biomes so I don't know how you'll go with that. 

-Slopsbucket

If the layout of biomes has changed, that will cause visible chunk boundary artifacts (large ugly cliffs in existing worlds where new chunks meet previously-generated chunks).

> Someone obviously noted that something funny was going on here because a switch was introduced to make Jungle Grass optional. But the reason Jungle Grass ends up everywhere is a direct result of the introduction of voxel_manip.
> 
> Just do a quick check yourself - start a new world and fly over it fast looking for jungle biomes or grassland biomes. They no longer exist.

-Slopsbucket

**Comment by slopsbucket** [comment]
Not quite, this only affects the biomes themselves, not mapgen.

As a quick test try swapping the current mapgen.lua with one from an older copy of Bucket_Game, you still get the same result.

I actually tested this quite a bit a few days ago, it was very frustrating because I do like "some" of the newer features in modern Final Minetest but to me this problem makes the game unplayable.

To see a real demonstration grab a copy of the version I'm currently using from 190620 at http://www.mediafire.com/file/0nmwza9jfwshveb/minetest-190620.tar.gz

Still uploading at the moment, give it a couple of minutes.

Go in to WonderWorld, to the east and slightly south of spawn is a small desert region, explore the boundaries of that region - should be open grasslands. Then explore the same area in a current version.

This problem does not lie in _game but in _core.

**Comment by poikilos** [comment]
@slopsbucket  You said the issue is in the core but only provided a copy of Bucket_Game in that zip. 
1. Can you provide a copy of the core from then? I don't have that.
2. Do you think the issue occurred later?

**Comment by slopsbucket** [comment]
Sorry, my mistake.

Here's a copy of the whole build kit, 340 Mb.

http://www.mediafire.com/file/qn9tpp5tgxunsqi/linux-minetest-kit-190620.tar.gz

Cheers,

Andrew.

**Comment by slopsbucket** [comment]
Hi Everyone,

Testing results show it to be a [b]_Game Issue[/b], and not _core.

We all get it wrong sometimes.

I wrote out my whole methodology below in the hope that some of you can do the same sort of trouble shooting when you have issues. The more people that can do this sort of testing the better Final Minetest will become, problems can get resolved properly instead of just being "patched" afterwards.

I'll make it easy for you here, you see, I'm lazy. I never learned to type properly and never will, sometimes if I get carried away I can use 3 fingers at once. So I use the Graphical User Interfaces where ever possible and appropriate. This makes me a good mediator between the hardcore keyboard monkeys and the average new users. I can do it all on the command line if I have to, there's certainly enough resources on the net to help my aging memory, but sometimes the GUI is a lot quicker and more efficient. If you can use both why wouldn't you?

Cheers,

Andrew.


There's a system for managing a program and the updates that get added to it called [b]git[/b]. Using this system on a program's "repository" you can easily turn back the clock, you can produce a version of the program from before the undesired updates were added. You can also make Git show you a list of all those updates. Very handy. Git is a very complex program that takes a long time to get to know, but we don't need to know all that. All we need to know is how to use 3 very basic and simple commands.

All we need to know is:

How to get that repository.
How to get that list of program changes.
How to extract the version of the program we want.

First of all you need to install Git. For linux users it's in your distro's repositories. I haven't used Windows in so long that I'm unable to comment for Windows users.

The first command is simply how to get hold of a particular program's repository. The repository will get placed in whatever folder your Terminal is open in, unless you like typing addresses in terminals all the time here's how I do it using my File Browser.

Open the file browser in your home folder, create a new folder, name it what you like, Mine-Dev or whatever. Right Click on that new folder and select "Open in Terminal". Then type the following command in to the terminal. Or just use the mouse to copy and pate the command, saves typing errors. And hit Enter of course:

git clone http://git.minetest.org/minetest/minetest.git

[b]Hot Tip[/b] [i]If your copy/paste includes the blank line under this command then the terminal will behave exactly the same as if you'd already hit the Enter key. The "next line" statement in the text operates the same as the command to execute from hitting the Enter key. In some instances this might be handy but mostly it's a trap.[/i]

That creates a folder called "minetest" inside your Mine-Dev or whatever you called it folder and it puts a full copy of the latest program's source code in there as well as all the files needed by Git. We'll consider this to be the "Prime" copy. We'll make this copy produce a list of the program changes, which are called "commits", but other than that we won't mess with it.

Your Terminal should have changed address to now be in the newly created "minetest" folder. Just to make sure anyway close that terminal. Right Click on that new minetest folder and choose "Open in Terminal". Either type in or copy/paste the following command:

git log >commits.txt

That creates a simple text file inside the minetest folder called (obviously) commits.txt that contains the full list of every change that has been made to the program. Most recent changes are at the top of the list. Each change or "commit" has a Hash Number, a very long hexidecimal number. We don't need to know much about this, except to think about it as an "identity key" for each particular program change. We also only need the first 8 digits of that hash number, the rest is meaningless to us.

So let's move on to the next step, we can now read the list of program changes and we're getting an idea of where our problems first came about by reading the comments that got with the commits.

We don't want to mess with that nice clean copy we just got off the net, instead, inside that Mine-Dev or whatever folder, create a new folder. Give it a name that relates to the problem you're looking for. In the example I demonstrate below I was looking for what I thought was a map generation problem, so I named my folder MapTest1. As I did further tests I made more folders with copies of the original inside them called MapTest2, MapTest3, etc. Be careful to never mess with the original, even rename it as a reminder if you like.

The command is simply "git checkout" followed by the first 8 digits of the particular commit's hash number, as an example:

git checkout c2c73d5b

So open your Terminal *inside the new copy you just made, not inside the original* and "checkout" what ever version you like. This recreates the source code as it was back when that change had just been made. You still need to compile it, then you need to add a copy of whatever_game to it.

Compile instructions. You want to create a version of minetest here that is "stand alone", you do not want it installed, it's temporary. Your Terminal is still open in that same folder. Or should be, if not open it in that folder again, and enter the following commands:

cmake . -DRUN_IN_PLACE=TRUE

When that one's done use this one:

make -j4

*Important - The last segment of that command is for how many processors your computer physically has. My processor has 6 cores so I used -j6.

Then you can test it. You just need to add a copy of the version of _game that you always use in the "games" folder. If it's still not behaving as you wish then create a new testing folder with a new copy of the repository and "checkout" from a different commit, compile and test again. Going through this process is not recommended for people with slow computers, it can be very time consuming.

[b]Hot Tip[/b] Your terminal remembers the last 20 or so commands you typed in. Pressing the Up Arrow key on your keyboard toggles through remembered commands. Keep pressing the Up Arrow until you see the command you want, then hit the Enter key to execute that command. If you're doing lots of checkouts and compiling them all this is very handy.

Eventually you can narrow it down to the exact commit that caused the problem you want fixed. Then (in Southpark style) you can contact the program administrator and say "You broke my toy! You bastard!" and let them know exactly which program change caused the problem. Please have a quick read through the example below it's the exact process I followed when lokking in to this biomes issue.

-------------------------------------------

At first I just wondered why there were so many trees and I couldn’t find any areas of open grassland where I could build.

Then when I started playing I couldn’t find any Jungle Grass, this is needed to get Cotton Seeds, you grow cotton to make Wool. I discovered that a switch had been introduced to disable Jungle Grass by default, I wondered why. I enabled Jungle Grass and discovered it was no longer just in jungles. It was everywhere. No wonder they added a switch to disable it.

Jungle Grass was everywhere, just like all kinds of trees were everywhere instead of in their native biomes. And there’s no grassland biomes any more, just endless trees.

1st test was an obvious one, take a copy of mapgen.lua from 190620 and put it in the new version of Bucket_Game, the same problem persisted. Putting the entire copy of Bucket_Game from 190620 caused a crash so I just replaced a few other individual files until I was convinced that it was not a _Game problem.

Next idea, do some checkouts in git to find when the issue started. The switch to disable Jungle Grass was added in the 190929 release so the problem has obviously existed since before then.

First checkout to try:

commit 2f289200c3a28bbbcccd03770b17ca0a0eb63ede
Author: OldCoder <oldcoder@yahoo.com>
Date: Sun Aug 18 03:02:59 2019 +0000

Disable leaf decay by default

Reason: there’s only two sets of core updates between this time and when the Jungle Grass switch was added, 190820 and 190925. Both of these include updates from the broken fork. I suspect that there’s too small a time difference between the commits of 190925 and the introduction of the Jungle Grass switch in the release on 190929, too short a time for someone to notice an issue, report it, and get the fix in. So my first suspect set of commits are those from 190820.

Checkout 2f289200
No compile errors.
Add copy of Bucket Game from 190620.
New map, mapgen 7, no mountains, no ridges, seed 70 – the wonderworld map.

[b]Result:[/b] Good, no mapgen or biome issues here.


Next checkout -

commit 19909753488a675376439c52a11725f19fd568b8
Author: OldCoder <oldcoder@yahoo.com>
Date: Tue Aug 20 11:08:39 2019 +0000
Add "player:get_meta" API function (#7202)

Only this and one other were added on 190820 and the other was only added 20 minutes earlier, I consider them to be a set.
No compile errors.
Add copy of Bucket Game from 190620.
New map, mapgen 7, no mountains, no ridges, seed 70 – the wonderworld map.

[b]Result:[/b] Good, no mapgen or biome issues here.



Next checkout – there were 5 commits added on 190925, I’ll treat them as a set and

Checkout c2c73d5b
No compile errors.
Add copy of Bucket Game from 190620.
New map, mapgen 7, no mountains, no ridges, seed 70 – the wonderworld map. Ridiculous.

[b]Result:[/b] Good, again no mapgen or biome issues here. So why did the Jungle Grass switch get added?



Try again, same freshly compiled copy but using a copy of Bucket_Game from 200230.

[b]Result: Problem:[/b] Trees every where and jumbled together again. No grasslands biomes.


So problem exists in [b]_Game[/b], not in _Core.

Need to double check. Try the _Game from 190620 in the 200230 release of the engine. This crashed last time I tried it.

[b]Result:[/b] Good. So why’d it crash last time? Mapgen is all as it should be.

[b]Confirmed:[/b] problem exists in _Game, not in _Core.

**Comment by poikilos** [comment]
@slopsbucket What you've shown here is not laziness, it is expert work. However, I only have so much time for testing. I am working on devops double since we have no one to help. I appreciate your bisection but please explain:
1. Better explanation than "all jumbled" or is that part of #389 ?
2. "wrong place": what where? Jungle grass in non-jungle areas, or are there other issues?
3. See #389 missing biomes It is a separate issue. Let's be clear.
4. Does #389 occur in old releases or not? I can't understand if you are bisecting two things at once or have not yet bisected #389 or if everything you said only applies to this issue, which I'm renaming to focus on the grass type issue.

**Comment by slopsbucket** [comment]
Points 1 and 2:
A picture tells a thousand words.
Please take a close look at this picture, you can see Pine Trees mixed in with Apple Trees, no Jungle Trees any where near. Please note the Jungle Grass under the trees.

Point 3
I believe the two issues are not separate but are both different symptoms of the same issue.

Point 4
This issue does not occur in the release of Bucket_Game from 190620,

Point 5
The switch to disable Jungle Grass was added in the 190929 release of Bucket_Game, it does not exist in the 190620 version.

In the versions 190929 and later maps are generated by default with no Jungle Grass, which is needed for gameplay.

Cheers,

Andrew.

![AfterTreesAPI](https://user-images.githubusercontent.com/48845069/80263761-dbf7ef80-86d0-11ea-8496-523d4a65145f.jpg)

**Comment by poikilos** [comment]
![screenshot_20200505_091043](https://user-images.githubusercontent.com/7557867/81069917-8da4d680-8eb0-11ea-9f93-76be7a48e86c.png)

Fixed in [200501](https://minetest.org/changes.html#200501)!

**Comment by poikilos** [comment]
Just for reference, here are some seeds along with wich biome they produce at 0,0,0 (the game converts the alphanumeric seeds you enter in the GUI into large numbers):
- aaa: grasslands
- ab: tundra (?) (permafrost_with_stones)
- abc: *_ocean (not surewhich subtype)
- ba: deciduous_forest (?) (various non-coniferous trees from default)
- bb: rainforest_swamp (?) (with rainforest nearby)
- bbb: *_ocean (not surewhich subtype)
- bc: desert
- ca: desert
- cb: rainforest_ocean (?) (with rainforests nearby on two sides)
- cc: *_ocean (not surewhich subtype)
