### ISSUE TITLE
Confused about scope and usage

### ISSUE THREAD

**Issue by xeruf** [Poikilos/EnlivenMinetest#593]
The readme says:

> see also webapp/README.md

but there is no webapp directory.
This is also mentioned multiple times throughout the readme.

So I am struggling to find out more about what ENLIVEN is and its quality.
Only found https://poikilos.org/2017/05/18/enliven-for-windows-a-minetest-infinite-block-world/ on your blog.

By the by, the PDF download on https://zahyest.com/ is broken.

**Comment by mckaygerhard** [comment]
interesting..mos of the documentation here is broken as i noted.. and mostly for windosers.. puff

**Comment by Poikilos** [comment]
Ill add text below where it fits into the documentation:

This repo has become more focused and now this repository only builds the ENLIVEN game (subgame for minetest), rather than essentially forking dozens of mods and adding them to a repo like many games ("subgames") do. You can download an old release in Releases. However, there are also several scripts related to installing or compiling Minetest and https://github.com/Poikilos/b3view.

The following projects were moved elsewhere for clarity:
- https://github.com/Poikilos/node-enliven-minetest: deferred, core feature replaced by in-game skin changing; uploading new skins may be re-added, but with a moderator approval system.
- https://github.com/Hierosoft/hierosoft (WIP Minetest "launcher" backend)
- https://github.com/Poikilos/mtanalyze (mostly used for upgrading run-in-place installs of any Minetest version, but has some WIP code for live maps that should be upgraded to work with Leaflet.js or replaced by MTSatellite).

The issue board here mostly exists since there are so many wontfix or ignored issues upstream and development on MT5 is mostly focused on features or arbitrary API changes that break mods. See:
- [Minetest's Scope Issue](https://poikilos.org/2020/05/09/minetest-scope-issue/)
- [Ramping in Sandbox Games](https://poikilos.org/2019/08/17/ramping-in-sandbox-games/)
- [Use animalmaterials and basic_materials for Minetest mods: low-level dependencies for better architecture](https://poikilos.org/2022/05/04/use-animalmaterials-and-basic_materials-for-minetest-mods-low-level-dependencies-for-better-architecture/)
- and comments related to API stability at [A Technical Explanation of the Minetest.org and Minetest.net Split](https://poikilos.org/2019/05/06/minetest-org-and-minetest-net-split/)

There are patches for mods, and scripts to help build and install Minetest and add patches. They are mostly for ENLIVEN but you can use them as well.

Some were merged upstream, such as:
- https://github.com/minetest-mods/ts_furniture/pull/6

You can apply whatever mods patches you want, but they are already in ENLIVEN (not all in the old release but will be if you build it). Most of the patches are also in Bucket_Game. The newest build script uses Bucket_Game as a content database to keep it rather small in comparison to Bucket_Game. In several cases, the patches have been accepted to upstream mods, such as:
- https://notabug.org/TenPlus1/farming/pulls/11
- https://github.com/D00Med/vehicles/pull/62#issuecomment-1368081408

or proposed such as:
- https://github.com/Poikilos/animalmaterials/blob/master/readme.md

or rejected for unspecified reasons :) , such as:
- https://notabug.org/TenPlus1/mobs_monster/issues/1

or I'm uncredited for unspecified reasons :), such as:
- https://notabug.org/TenPlus1/pie/commits/master/textures/pie_inv.png
  - fixes https://notabug.org/TenPlus1/pie/issues/1

In some cases I may use maintained versions of unmaintained mods or ones where I have differences of direction such as:
- https://github.com/Poikilos/slimenodes
- https://github.com/Poikilos/prestibags
- https://github.com/Poikilos/mobs_sky
- https://github.com/Poikilos/metatools
- https://github.com/Poikilos/orichalcum
- https://github.com/Poikilos/throwing
- https://github.com/Poikilos/throwing_arrows
- https://github.com/Poikilos/titanium
- https://github.com/Poikilos/vines (still not working for me, forked or not, on any version of Minetest)
- https://github.com/Poikilos/compassgps
- https://github.com/Poikilos/whinny (mostly for Bucket_Game)
- https://github.com/Poikilos/travelnet -- see:
  - https://github.com/Sokomine/travelnet/pull/45
  - https://github.com/Sokomine/travelnet/pull/46
  - https://github.com/Sokomine/travelnet/pull/47
- https://github.com/Poikilos/birthstones
- https://github.com/Poikilos/xtraarmor
- https://github.com/Poikilos/tsm_pyramids (mostly for Bucket_Game)
- https://github.com/Poikilos/ts_furniture
- https://github.com/Poikilos/filter (@MoNTE48 proposed it to comission me, but though it was exactly to his specifications it had ~547 lines instead of 500 so he rejected it :clown_face: )
- https://github.com/Poikilos/loot
- https://github.com/Poikilos/nether (provides nodes separately from the realm--See  [Use animalmaterials and basic_materials for Minetest mods: low-level dependencies for better architecture](https://poikilos.org/2022/05/04/use-animalmaterials-and-basic_materials-for-minetest-mods-low-level-dependencies-for-better-architecture/))
- https://github.com/Poikilos/hbsprint (WIP)
- https://github.com/Poikilos/bushes_soil (for multiplayer balancing)
- https://github.com/Poikilos/emeralds (mostly for Bucket_Game)
- https://github.com/Poikilos/camera (WIP)

Or new mods:
- https://github.com/Poikilos/trmp_minetest_game


I'll update the documentation today accordingly. I'll also document where the server is: minetest.io:30023. Thanks for reporting the issue.

**Comment by Poikilos** [comment]
> interesting..mos of the documentation here is broken as i noted.. and mostly for windosers.. puff

That's because windoze users need the most help :) That's where the [launcher (WIP, backend only for now)](https://github.com/Hierosoft/hierosoft) will be the most helpful. I'll commit some/all of my notes from my previous comment to docs though.

**Comment by Poikilos** [comment]
> By the by, the PDF download on https://zahyest.com/ is broken.

Fixed, thanks.

**Comment by mckaygerhard** [comment]
> > interesting..mos of the documentation here is broken as i noted.. and mostly for windosers.. puff
> 
> That's because windoze users need the most help :) That's where the [launcher (WIP, backend only for now)](https://github.com/Hierosoft/hierosoft) will be the most helpful. I'll commit some/all of my notes from my previous comment to docs though.

windoze stupid users just must paid if there are no skills to manage their instalattin .. USERS = only usage, USER does not means admin or coder.. so must paid to us to provide those installations..

**Comment by mckaygerhard** [comment]
> This repo has become more focused and now this repository only builds the ENLIVEN game (subgame for minetest), rather than essentially forking dozens of mods and adding them to a repo like many games ("subgames") do.

i checked only 50% of the info.. puff was so huge.. i can helpo in such cos still there are some misctakes and fails.. but will need more time.. the information and files involved are huge
